In [1]:
import numpy as np
from IPython.display import display
from sklearn import preprocessing

In [4]:
x = np.array(np.random.randint(-3,3,9).reshape(3,3))
display(x)

array([[ 1, -3,  1],
       [ 1, -1,  0],
       [ 0,  2,  1]])

## Min-Max规范化：将原始数据变换到【0,1】空间
** 公式：新数值 = （原数值 - 最小值）/（最大值 - 最小值）
* 按列计算

In [5]:
min_max_scaler = preprocessing.MinMaxScaler()
minmax_x = min_max_scaler.fit_transform(x)
display(minmax_x)

array([[1. , 0. , 1. ],
       [1. , 0.4, 0. ],
       [0. , 1. , 1. ]])

## Z-Score规范化：将原始数据规范到同一标准进行比较
** 在scikit-learn库中使用preprocessing.scale()函数，可以直接将给定数据进行Z-Score规范化

** 公式：新数值 = （原数值 - 均值）/（标准差）

In [6]:
scaled_x = preprocessing.scale(x)
display(scaled_x)

array([[ 0.70710678, -1.13554995,  0.70710678],
       [ 0.70710678, -0.16222142, -1.41421356],
       [-1.41421356,  1.29777137,  0.70710678]])

## 小数定标规范化：移动小数点位置进行规范化
** 新数值 = 原数值 / 10的x次方  --x看原数值的最大值的绝对值有几位数

In [14]:
y = np.array(np.random.randint(-3,3,9).reshape(3,3))
display(y)

array([[ 0,  1, -3],
       [-1, -3,  1],
       [ 2,  2,  0]])

In [18]:
j = np.ceil(np.log10(np.max(abs(y))))  # 向上取整
display(j)
a = y / (10**j)
display(a)

1.0

array([[ 0. ,  0.1, -0.3],
       [-0.1, -0.3,  0.1],
       [ 0.2,  0.2,  0. ]])

### 假设属性income最小值为5000，最大值为58000，属性income为16000元被转化为多少？用min-max规范化方法

In [7]:
dn = np.array([[5000],[16000],[58000]])
display(dn)
min_max_sacler = preprocessing.MinMaxScaler()
x = min_max_scaler.fit_transform(dn)
display(x)

array([[ 5000],
       [16000],
       [58000]])

array([[0.        ],
       [0.20754717],
       [1.        ]])